### ISSUE TITLE
SMuFF on Klipper and V5 build

### ISSUE THREAD

**Issue by flopana77** [technik-gegg/SMuFF-1.1#14]
Hi technik-geeg
I am a looking at running the SMuFF via Klipper. That said, I wanted to build the V5 and didn't put my mail address in the donation...Is there any way we can get in contact regarding the stl-files and to discuss the Klipper implementation later on?
Cheers
PS: Sorry for contacting this way...didn't figure any other option...

**Comment by flopana77** [comment]
Once the build is ready to tackle Klipper, we'll talk again 👍

**Comment by technik-gegg** [comment]
We'll do.
