### ISSUE TITLE
TWI problem

### ISSUE THREAD

**Issue by luismello** [technik-gegg/SMuFF-1.1#18]
After turn ON, it has continuous beep, I checked and the file size is 2200, but the SMUFF.CFG file has 2378, I changed the file size limit and Smuff turn ON.

But the Main Menu doesn't appear.

**Comment by technik-gegg** [comment]
Have you read the [README of this release](https://github.com/technik-gegg/SMuFF-1.1/tree/SMuFF-2.0-(Experimental)#recent-changes)? There have been a lot of changes for menus and config files.

**Comment by luismello** [comment]
hi

I put Menus, Options and Sound, but the menus still have a problem


![IMG_20201109_154333515 1](https://user-images.githubusercontent.com/21027864/98583137-a6000e80-22a2-11eb-8bd7-f19090748ef7.jpg)
![IMG_20201109_154401446 1](https://user-images.githubusercontent.com/21027864/98583190-bb753880-22a2-11eb-838e-3344edcc2e10.jpg)

**Comment by technik-gegg** [comment]
I'm working on it, please stay tuned.

Nice wiring btw. so... colorful ;o)

**Comment by luismello** [comment]
Hi TG

I will buy the BTT Mini12864 V1.0.

I did with the threads I had at home, hehe

**Comment by technik-gegg** [comment]
@luismello 
Checked in 2.13. Please try it and let me know if there are still issues.

**Comment by luismello** [comment]
Hi TG

Version 2.13 did not solve my problem with Oled.

**Comment by technik-gegg** [comment]
Is your OLED basically working and has a distorted screen or does it freeze up at some point?
