### ISSUE TITLE
Klipper via macros and shell commands? 

### ISSUE THREAD

**Issue by Alfiegerner** [technik-gegg/SMuFF-1.1#23]
Hi,

Really interested in this project and have a donation in for a manual. But I'm wed to klipper for this printer. I have seen the faq and previously raised topics on this but have not seen this particular idea addressed.

I was wondering if using klippers customisable macros could help integration, e. g. 

setting up tool change macros on klipper, which sent text over serial (via shell commands) to the smuff control board as per octoprint plugin.

What i don't know is how complicated that would get, e.g. how many macros, how much 2 way comms, error handling etc, but my thinking is that should be encapsulated in the octoprint project? Possibly extracted into a generic serial interface project?

I saw your comment that other tool change systems are available for klipper, and have been thinking of a 5 extruder, multi line switching / filament shaping solution, but much prefer the smuff if i can make it work - any other suggestions very welcome. 

Thanks!

**Comment by technik-gegg** [comment]
Mind you discussing this topic over on Discord, since it's not really an issue of the SMuFF firmware but rather a feature in Klipper?
