### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by biancapascal** [technik-gegg/SMuFF-1.1#24]
I have SKR E3-DIP V1.1 as recommended.
In the build manuel you speak then after compiling to copy de firmware.bin from the build BIGTREE_SKR_MINI_E3DIP_SD.

But if the code is ready with creating all the builds, there is no folder in the build with that name.
Maybe i'm stupped but after a lot of time spending to build this project i'm missing this part.

Please help.

**Comment by technik-gegg** [comment]
Please join me on Discord. It's easier to have a communcation there.

**Comment by biancapascal** [comment]
link?

**Comment by technik-gegg** [comment]
https://discord.com/invite/BzZ3rBf
