### ISSUE TITLE
Firmware Compile for Artillery Ruby board

### ISSUE THREAD

**Issue by JoJos1220** [technik-gegg/SMuFF-1.1#26]
Hi,

i have a question regarding the build of the Firmware. In the past I have changed an Artillery Ruby board of my Sidewinder X2 because of an Hotend Issue. I have found out that the Thiristor is blown up....actually a trivial thing - i can change it and it run OK until i saw this project:
Currently I am thinking about building a SMUFF for myself and i want to use this Artillery Ruby Mainboard instead of the SKR mini board because it would actually fit perfectly and the Thermistor Output for the Hotend Heating is not needed for it.
Is it possible to build the Firmware for the Artillery Ruby board? Have someone experience with it?

**Comment by technik-gegg** [comment]
Please join us on [Discord](https://discord.com/invite/BzZ3rBf) for such questions.
