### ISSUE TITLE
Is Ws2812b just optional?

### ISSUE THREAD

**Issue by NamkingWIN** [technik-gegg/SMuFF-1.1#3]
I see in the list of customized display board do not list ws2812b but in the schematic has one. Can I remove that on the oled board?

**Comment by technik-gegg** [comment]
Yep, totally optional. It was meant to be used as an additional signalling feature but as of yet, the FastLED library does not compile on the STM32 environment.
Maybe some day in the future.

**Comment by NamkingWIN** [comment]
Ok, can 2 resistor 10k also remove?

**Comment by technik-gegg** [comment]
No. That one is needed for the encoder.

**Comment by NamkingWIN** [comment]
Can you re-draw schematic exactly? Thanks!
