### ISSUE TITLE
Maybe booting failed even oled show ready!

### ISSUE THREAD

**Issue by NamkingWIN** [technik-gegg/SMuFF-1.1#5]
Hi,
On the oled show “I ready” but at the left-down corner show “0” instead the free memory left. What I am getting error?
![F7111A2D-A329-4397-BAFB-5C0646F688EA](https://user-images.githubusercontent.com/34998186/71389429-ed4fc300-262e-11ea-8547-ffb38f7cac0c.jpeg)

**Comment by technik-gegg** [comment]
That's not an error, that's by design. The memory display works reliably only on the ATMega CPUs but not on STM32. Hence, this information has been replaced by the amount of filament feed on the SKR board.
It's all as it's supposed to be and it's documented somewhere in the release notes.

If you long press the encoder button, it'll take you into the **Settings** menu.

**Comment by everything-tech-related** [comment]
I'm at the same point now. Long press doesnt work for me. Also if I edit the config it gets corrupted. Even changing UseServo: false to true makes it not work

**Comment by technik-gegg** [comment]
Well guys, again, check your wiring!

This is, what it's supposed to be: 

![Encoder-Wiring](https://user-images.githubusercontent.com/44457073/71554093-eb18aa80-2a1a-11ea-87ce-85fed0e2a939.png)

I'm pretty sure you've left out some connections.

**Comment by everything-tech-related** [comment]
In the pic you have of the lcd board. The  Rotary knob section...S1= pin 9/BT-ENC. And  S2= GND.

The pic above shows the opposite. I tried both but same results.

**Comment by technik-gegg** [comment]
That doesn't matter at all. It's just a switch that shorts to GND. Will work either way.

**Comment by technik-gegg** [comment]
Maybe the flat ribbon cable you're using to connect to the board sucks. Try replacing it.

**Comment by everything-tech-related** [comment]
Yea I thought about that so i tried a secon ribbon and and also went straight dupont to the skr connector. I'll try another rotary encoder tomorrow. 

As for the SMUFF.cfg parser check says valid but it never boots whenever I edit and save. Only works when I just rename your original file.

**Comment by technik-gegg** [comment]
I've uploaded a CFG for the servo variant. Try this one.

What does the ArduinoJson assistant say about the Memory Pool Size for ESP32/ESP8266? It's supposed to be somewhere around 1764 bytes.

**Comment by everything-tech-related** [comment]
I'm not at the computer right now but If I remember correctly it was +1800. Can you upload cfg servo for duet please. I know it's simple as changing deuet3d to true but any changes I make results in it not working.

**Comment by technik-gegg** [comment]
Did that.

**Comment by everything-tech-related** [comment]
Stuck at "reading config" with the file you just uploaded :(

**Comment by technik-gegg** [comment]
Try a different SD-Card, formatted with standard FAT.

**Comment by everything-tech-related** [comment]
Did that, still stuck. I only have 2 sdcard that can format with standard FAT

**Comment by everything-tech-related** [comment]
This is so weird. The original SMUFF_DUET.CFG works (as in boots but still no encoder function) when I rename it. But the new ones dont.

**Comment by technik-gegg** [comment]
Yep, that's weird... I just did the same without any issues.
